INFO 2023-10-07 10:24:22,987 autoreload 6404 3276 Watching for file changes with StatReloader
WARNING 2023-10-07 10:24:27,273 log 6404 3368 Not Found: /
WARNING 2023-10-07 10:24:27,273 basehttp 6404 3368 "GET / HTTP/1.1" 404 4279
INFO 2023-10-07 10:25:42,552 autoreload 6208 17556 Watching for file changes with StatReloader
WARNING 2023-10-07 10:25:44,939 log 6208 7836 Not Found: /
WARNING 2023-10-07 10:25:44,939 basehttp 6208 7836 "GET / HTTP/1.1" 404 4454
INFO 2023-10-07 10:25:52,092 basehttp 6208 2932 "GET /add_goods HTTP/1.1" 301 0
INFO 2023-10-07 10:25:52,138 basehttp 6208 9964 "GET /add_goods/ HTTP/1.1" 200 1669
INFO 2023-10-07 11:15:19,866 autoreload 19052 8652 Watching for file changes with StatReloader
WARNING 2023-10-07 11:15:23,493 log 19052 4884 Not Found: /
WARNING 2023-10-07 11:15:23,494 basehttp 19052 4884 "GET / HTTP/1.1" 404 4454
INFO 2023-10-07 11:15:38,629 basehttp 19052 11188 "GET /admin HTTP/1.1" 301 0
INFO 2023-10-07 11:15:38,629 basehttp 19052 14552 "GET /admin/ HTTP/1.1" 302 0
INFO 2023-10-07 11:15:38,708 basehttp 19052 14552 "GET /admin/login/?next=/admin/ HTTP/1.1" 200 4181
INFO 2023-10-07 11:15:38,959 basehttp 19052 14476 "GET /static/admin/css/dark_mode.css HTTP/1.1" 200 2929
INFO 2023-10-07 11:15:38,959 basehttp 19052 16852 "GET /static/admin/css/login.css HTTP/1.1" 200 958
INFO 2023-10-07 11:15:38,959 basehttp 19052 5008 "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 200 2694
INFO 2023-10-07 11:15:38,959 basehttp 19052 3500 "GET /static/admin/js/theme.js HTTP/1.1" 200 1943
INFO 2023-10-07 11:15:38,959 basehttp 19052 2648 "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 200 3063
INFO 2023-10-07 11:15:38,959 basehttp 19052 14552 "GET /static/admin/css/base.css HTTP/1.1" 200 21207
INFO 2023-10-07 11:15:38,959 basehttp 19052 14476 "GET /static/admin/css/responsive.css HTTP/1.1" 200 18533
INFO 2023-10-07 11:16:48,296 autoreload 7188 2944 Watching for file changes with StatReloader
WARNING 2023-10-07 11:16:50,571 log 7188 14400 Not Found: /
WARNING 2023-10-07 11:16:50,571 basehttp 7188 14400 "GET / HTTP/1.1" 404 4454
INFO 2023-10-07 11:17:03,043 basehttp 7188 17024 "GET /admin/ HTTP/1.1" 302 0
INFO 2023-10-07 11:17:03,116 basehttp 7188 17024 "GET /admin/login/?next=/admin/ HTTP/1.1" 200 4267
INFO 2023-10-07 11:17:03,210 basehttp 7188 17024 - Broken pipe from ('127.0.0.1', 56252)
INFO 2023-10-07 22:16:43,875 autoreload 16296 7624 Watching for file changes with StatReloader
WARNING 2023-10-07 22:16:46,785 log 16296 8432 Not Found: /
WARNING 2023-10-07 22:16:46,796 basehttp 16296 8432 "GET / HTTP/1.1" 404 4454
INFO 2023-10-07 22:16:58,096 basehttp 16296 4596 "GET /admin/ HTTP/1.1" 302 0
INFO 2023-10-07 22:16:58,253 basehttp 16296 4596 "GET /admin/login/?next=/admin/ HTTP/1.1" 200 4267
INFO 2023-10-07 22:16:58,296 basehttp 16296 4596 "GET /static/admin/css/base.css HTTP/1.1" 304 0
INFO 2023-10-07 22:16:58,296 basehttp 16296 9400 "GET /static/admin/css/dark_mode.css HTTP/1.1" 304 0
INFO 2023-10-07 22:16:58,300 basehttp 16296 4596 "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 304 0
INFO 2023-10-07 22:16:58,300 basehttp 16296 1824 "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 304 0
INFO 2023-10-07 22:16:58,300 basehttp 16296 11764 "GET /static/admin/css/login.css HTTP/1.1" 304 0
INFO 2023-10-07 22:16:58,300 basehttp 16296 9400 "GET /static/admin/js/theme.js HTTP/1.1" 304 0
INFO 2023-10-07 22:16:58,300 basehttp 16296 5928 "GET /static/admin/css/responsive.css HTTP/1.1" 304 0
ERROR 2023-10-07 22:19:19,385 log 16296 10988 Internal Server Error: /admin/login/
Traceback (most recent call last):
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\db\backends\base\base.py", line 313, in _commit
    return self.connection.commit()
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\views\decorators\cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\contrib\admin\sites.py", line 441, in login
    return LoginView.as_view(**defaults)(request)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\views\decorators\debug.py", line 92, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\utils\decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\views\decorators\cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\contrib\auth\views.py", line 90, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\views\generic\edit.py", line 153, in post
    return self.form_valid(form)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\contrib\auth\views.py", line 109, in form_valid
    auth_login(self.request, form.get_user())
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\contrib\auth\__init__.py", line 118, in login
    request.session.cycle_key()
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\contrib\sessions\backends\base.py", line 304, in cycle_key
    self.create()
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\contrib\sessions\backends\db.py", line 54, in create
    self.save(must_create=True)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\contrib\sessions\backends\db.py", line 85, in save
    with transaction.atomic(using=using):
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\db\transaction.py", line 263, in __exit__
    connection.commit()
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\db\backends\base\base.py", line 337, in commit
    self._commit()
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\db\backends\base\base.py", line 312, in _commit
    with debug_transaction(self, "COMMIT"), self.wrap_database_errors:
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\db\backends\base\base.py", line 313, in _commit
    return self.connection.commit()
django.db.utils.OperationalError: database is locked
ERROR 2023-10-07 22:19:19,401 basehttp 16296 10988 "POST /admin/login/?next=/admin/ HTTP/1.1" 500 176101
INFO 2023-10-07 22:19:30,228 basehttp 16296 10988 "GET /admin/login/?next=/admin/ HTTP/1.1" 200 4267
WARNING 2023-10-07 22:20:25,254 log 16296 17228 Not Found: /
WARNING 2023-10-07 22:20:25,254 basehttp 16296 17228 "GET / HTTP/1.1" 404 4454
INFO 2023-10-07 22:20:27,187 basehttp 16296 17156 "GET /admin/login/?next=/admin/ HTTP/1.1" 200 4267
INFO 2023-10-07 22:20:27,372 basehttp 16296 17156 "GET /static/admin/css/base.css HTTP/1.1" 200 21207
INFO 2023-10-07 22:20:48,425 basehttp 16296 8852 "POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
INFO 2023-10-07 22:20:48,488 basehttp 16296 8852 "GET /admin/ HTTP/1.1" 200 5858
INFO 2023-10-07 22:20:48,519 basehttp 16296 8852 "GET /static/admin/css/dashboard.css HTTP/1.1" 200 441
INFO 2023-10-07 22:20:48,566 basehttp 16296 8852 "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
INFO 2023-10-07 22:20:48,566 basehttp 16296 14028 "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380
INFO 2023-10-07 22:24:33,052 basehttp 16296 17036 "GET /admin/auth/user/add/ HTTP/1.1" 200 10994
INFO 2023-10-07 22:24:33,142 basehttp 16296 5212 "GET /admin/jsi18n/ HTTP/1.1" 200 16066
INFO 2023-10-07 22:24:33,142 basehttp 16296 17036 "GET /static/admin/css/forms.css HTTP/1.1" 200 9047
INFO 2023-10-07 22:24:33,142 basehttp 16296 3768 "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 200 8943
INFO 2023-10-07 22:24:33,156 basehttp 16296 4684 "GET /static/admin/js/jquery.init.js HTTP/1.1" 200 347
INFO 2023-10-07 22:24:33,156 basehttp 16296 3768 "GET /static/admin/js/urlify.js HTTP/1.1" 200 7887
INFO 2023-10-07 22:24:33,157 basehttp 16296 5212 "GET /static/admin/js/actions.js HTTP/1.1" 200 7872
INFO 2023-10-07 22:24:33,163 basehttp 16296 4684 "GET /static/admin/js/prepopulate_init.js HTTP/1.1" 200 586
INFO 2023-10-07 22:24:33,168 basehttp 16296 5212 "GET /static/admin/js/change_form.js HTTP/1.1" 200 606
INFO 2023-10-07 22:24:33,168 basehttp 16296 17036 "GET /static/admin/js/prepopulate.js HTTP/1.1" 200 1531
INFO 2023-10-07 22:24:33,169 basehttp 16296 5020 "GET /static/admin/js/core.js HTTP/1.1" 200 5682
INFO 2023-10-07 22:24:33,169 basehttp 16296 4684 "GET /static/admin/css/widgets.css HTTP/1.1" 200 11900
INFO 2023-10-07 22:24:33,174 basehttp 16296 3768 "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 200 232381
INFO 2023-10-07 22:24:33,182 basehttp 16296 5112 "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 200 292458
INFO 2023-10-07 22:24:44,242 basehttp 16296 5112 "GET /admin/ HTTP/1.1" 200 5858
INFO 2023-10-07 22:24:46,292 basehttp 16296 5112 "GET /admin/auth/group/ HTTP/1.1" 200 7647
INFO 2023-10-07 22:24:46,339 basehttp 16296 3768 "GET /admin/jsi18n/ HTTP/1.1" 200 16066
INFO 2023-10-07 22:24:46,339 basehttp 16296 5112 "GET /static/admin/css/changelists.css HTTP/1.1" 200 6566
INFO 2023-10-07 22:24:46,354 basehttp 16296 5212 "GET /static/admin/js/filters.js HTTP/1.1" 200 978
INFO 2023-10-07 22:24:46,370 basehttp 16296 3768 "GET /static/admin/img/search.svg HTTP/1.1" 200 458
INFO 2023-10-07 22:24:46,370 basehttp 16296 5112 "GET /static/admin/img/tooltag-add.svg HTTP/1.1" 200 331
INFO 2023-10-07 22:46:57,531 basehttp 16296 6432 "GET /admin/auth/user/add/ HTTP/1.1" 200 10994
INFO 2023-10-07 22:46:57,578 basehttp 16296 6432 "GET /admin/jsi18n/ HTTP/1.1" 200 16066
INFO 2023-10-07 22:47:47,236 basehttp 16296 6432 "POST /admin/auth/user/add/ HTTP/1.1" 302 0
INFO 2023-10-07 22:47:47,314 basehttp 16296 6432 "GET /admin/auth/user/2/change/ HTTP/1.1" 200 22769
INFO 2023-10-07 22:47:47,361 basehttp 16296 6432 "GET /admin/jsi18n/ HTTP/1.1" 200 16066
INFO 2023-10-07 22:47:47,393 basehttp 16296 7768 "GET /static/admin/js/admin/DateTimeShortcuts.js HTTP/1.1" 200 19319
INFO 2023-10-07 22:47:47,393 basehttp 16296 4984 "GET /static/admin/js/calendar.js HTTP/1.1" 200 8466
INFO 2023-10-07 22:47:47,393 basehttp 16296 15940 "GET /static/admin/js/SelectBox.js HTTP/1.1" 200 4530
INFO 2023-10-07 22:47:47,393 basehttp 16296 6432 "GET /static/admin/js/SelectFilter2.js HTTP/1.1" 200 15292
INFO 2023-10-07 22:47:47,440 basehttp 16296 7768 "GET /static/admin/img/icon-yes.svg HTTP/1.1" 200 436
INFO 2023-10-07 22:47:47,455 basehttp 16296 15940 "GET /static/admin/img/icon-clock.svg HTTP/1.1" 200 677
INFO 2023-10-07 22:47:47,471 basehttp 16296 7768 "GET /static/admin/img/selector-icons.svg HTTP/1.1" 200 3291
INFO 2023-10-07 22:47:47,471 basehttp 16296 4984 "GET /static/admin/img/icon-calendar.svg HTTP/1.1" 200 1086
INFO 2023-10-07 22:48:34,669 basehttp 16296 6432 "POST /admin/auth/user/2/change/ HTTP/1.1" 302 0
INFO 2023-10-07 22:48:34,699 basehttp 16296 6432 "GET /admin/auth/user/ HTTP/1.1" 200 11981
INFO 2023-10-07 22:48:34,734 basehttp 16296 7768 "GET /admin/jsi18n/ HTTP/1.1" 200 16066
INFO 2023-10-07 22:48:34,781 basehttp 16296 7768 "GET /static/admin/img/sorting-icons.svg HTTP/1.1" 200 1097
INFO 2023-10-07 23:03:26,155 basehttp 16296 7228 "GET /admin/auth/user/2/change/ HTTP/1.1" 200 22534
INFO 2023-10-07 23:03:26,218 basehttp 16296 7228 "GET /admin/jsi18n/ HTTP/1.1" 200 16066
INFO 2023-10-07 23:03:33,065 basehttp 16296 7228 "POST /admin/auth/user/2/change/ HTTP/1.1" 302 0
INFO 2023-10-07 23:03:33,081 basehttp 16296 7228 "GET /admin/auth/user/ HTTP/1.1" 200 11981
INFO 2023-10-07 23:03:33,116 basehttp 16296 7228 "GET /admin/jsi18n/ HTTP/1.1" 200 16066
INFO 2023-10-07 23:10:41,286 autoreload 16296 7624 D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\online_shop\models.py changed, reloading.
INFO 2023-10-07 23:10:42,342 autoreload 7928 3396 Watching for file changes with StatReloader
INFO 2023-10-08 14:59:37,164 autoreload 824 6432 Watching for file changes with StatReloader
WARNING 2023-10-08 14:59:40,778 log 824 17920 Not Found: /
WARNING 2023-10-08 14:59:40,779 basehttp 824 17920 "GET / HTTP/1.1" 404 4454
INFO 2023-10-08 14:59:45,265 basehttp 824 10808 "GET /admin/auth/user/ HTTP/1.1" 200 12648
INFO 2023-10-08 14:59:45,339 basehttp 824 17116 "GET /admin/jsi18n/ HTTP/1.1" 200 16066
INFO 2023-10-08 14:59:45,489 basehttp 824 10808 "GET /static/admin/img/search.svg HTTP/1.1" 200 458
INFO 2023-10-08 14:59:45,505 basehttp 824 16820 "GET /static/admin/img/icon-yes.svg HTTP/1.1" 200 436
INFO 2023-10-08 14:59:45,510 basehttp 824 17876 "GET /static/admin/css/responsive.css HTTP/1.1" 200 18533
INFO 2023-10-08 14:59:45,545 basehttp 824 17116 "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
INFO 2023-10-08 14:59:45,545 basehttp 824 15344 "GET /static/admin/img/sorting-icons.svg HTTP/1.1" 200 1097
INFO 2023-10-08 14:59:45,546 basehttp 824 11648 "GET /static/admin/img/tooltag-add.svg HTTP/1.1" 200 331
INFO 2023-10-08 14:59:48,318 basehttp 824 17116 "GET /admin/auth/user/ HTTP/1.1" 200 12648
INFO 2023-10-08 14:59:48,349 basehttp 824 17116 "GET /static/admin/css/base.css HTTP/1.1" 304 0
INFO 2023-10-08 14:59:48,349 basehttp 824 16820 "GET /static/admin/js/theme.js HTTP/1.1" 304 0
INFO 2023-10-08 14:59:48,350 basehttp 824 11648 "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 304 0
INFO 2023-10-08 14:59:48,352 basehttp 824 15344 "GET /static/admin/css/dark_mode.css HTTP/1.1" 304 0
INFO 2023-10-08 14:59:48,353 basehttp 824 10808 "GET /static/admin/css/changelists.css HTTP/1.1" 304 0
INFO 2023-10-08 14:59:48,363 basehttp 824 16280 "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 304 0
INFO 2023-10-08 14:59:48,366 basehttp 824 11648 "GET /static/admin/js/jquery.init.js HTTP/1.1" 304 0
INFO 2023-10-08 14:59:48,369 basehttp 824 15344 "GET /static/admin/js/core.js HTTP/1.1" 304 0
INFO 2023-10-08 14:59:48,369 basehttp 824 16820 "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 304 0
INFO 2023-10-08 14:59:48,371 basehttp 824 10808 "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 304 0
INFO 2023-10-08 14:59:48,378 basehttp 824 17116 "GET /admin/jsi18n/ HTTP/1.1" 200 16066
INFO 2023-10-08 14:59:48,379 basehttp 824 16280 "GET /static/admin/js/actions.js HTTP/1.1" 304 0
INFO 2023-10-08 14:59:48,381 basehttp 824 11648 "GET /static/admin/js/urlify.js HTTP/1.1" 304 0
INFO 2023-10-08 14:59:48,386 basehttp 824 15344 "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 304 0
INFO 2023-10-08 14:59:48,386 basehttp 824 16820 "GET /static/admin/js/prepopulate.js HTTP/1.1" 304 0
INFO 2023-10-08 14:59:48,387 basehttp 824 10808 "GET /static/admin/js/filters.js HTTP/1.1" 304 0
INFO 2023-10-08 14:59:48,387 basehttp 824 17116 "GET /static/admin/css/responsive.css HTTP/1.1" 304 0
INFO 2023-10-08 14:59:56,228 basehttp 824 17116 "GET /admin HTTP/1.1" 301 0
INFO 2023-10-08 14:59:56,243 basehttp 824 10808 "GET /admin/ HTTP/1.1" 200 7999
INFO 2023-10-08 14:59:56,280 basehttp 824 15344 "GET /static/admin/css/dashboard.css HTTP/1.1" 304 0
INFO 2023-10-08 14:59:56,304 basehttp 824 15344 "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380
ERROR 2023-10-08 15:00:00,588 log 824 10808 Internal Server Error: /admin/online_shop/product/
Traceback (most recent call last):
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
sqlite3.OperationalError: no such table: online_shop_product

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\contrib\admin\options.py", line 688, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\utils\decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\views\decorators\cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\contrib\admin\sites.py", line 242, in inner
    return view(request, *args, **kwargs)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\utils\decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\contrib\admin\options.py", line 1926, in changelist_view
    cl = self.get_changelist_instance(request)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\contrib\admin\options.py", line 836, in get_changelist_instance
    return ChangeList(
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\contrib\admin\views\main.py", line 123, in __init__
    self.get_results(request)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\contrib\admin\views\main.py", line 279, in get_results
    result_count = paginator.count
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\utils\functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\core\paginator.py", line 93, in count
    return c()
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\db\models\query.py", line 608, in count
    return self.query.get_count(using=self.db)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\db\models\sql\query.py", line 568, in get_count
    return obj.get_aggregation(using, {"__count": Count("*")})["__count"]
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\db\models\sql\query.py", line 554, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
django.db.utils.OperationalError: no such table: online_shop_product
ERROR 2023-10-08 15:00:00,599 basehttp 824 10808 "GET /admin/online_shop/product/ HTTP/1.1" 500 180289
INFO 2023-10-08 15:00:03,499 basehttp 824 10808 "GET /admin/ HTTP/1.1" 200 7999
ERROR 2023-10-08 15:00:04,621 log 824 10808 Internal Server Error: /admin/online_shop/category/
Traceback (most recent call last):
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
sqlite3.OperationalError: no such table: online_shop_category

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\contrib\admin\options.py", line 688, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\utils\decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\views\decorators\cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\contrib\admin\sites.py", line 242, in inner
    return view(request, *args, **kwargs)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\utils\decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\contrib\admin\options.py", line 1926, in changelist_view
    cl = self.get_changelist_instance(request)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\contrib\admin\options.py", line 836, in get_changelist_instance
    return ChangeList(
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\contrib\admin\views\main.py", line 123, in __init__
    self.get_results(request)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\contrib\admin\views\main.py", line 279, in get_results
    result_count = paginator.count
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\utils\functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\core\paginator.py", line 93, in count
    return c()
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\db\models\query.py", line 608, in count
    return self.query.get_count(using=self.db)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\db\models\sql\query.py", line 568, in get_count
    return obj.get_aggregation(using, {"__count": Count("*")})["__count"]
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\db\models\sql\query.py", line 554, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
django.db.utils.OperationalError: no such table: online_shop_category
ERROR 2023-10-08 15:00:04,625 basehttp 824 10808 "GET /admin/online_shop/category/ HTTP/1.1" 500 180340
INFO 2023-10-08 15:00:06,472 basehttp 824 10808 "GET /admin/ HTTP/1.1" 200 7999
INFO 2023-10-08 15:00:11,272 basehttp 824 10808 "GET /admin/auth/user/2/change/ HTTP/1.1" 200 24021
INFO 2023-10-08 15:00:11,324 basehttp 824 15344 "GET /admin/jsi18n/ HTTP/1.1" 200 16066
INFO 2023-10-08 15:00:11,326 basehttp 824 16820 "GET /static/admin/css/forms.css HTTP/1.1" 304 0
INFO 2023-10-08 15:00:11,331 basehttp 824 15344 "GET /static/admin/js/calendar.js HTTP/1.1" 304 0
INFO 2023-10-08 15:00:11,335 basehttp 824 16280 "GET /static/admin/js/SelectFilter2.js HTTP/1.1" 304 0
INFO 2023-10-08 15:00:11,336 basehttp 824 11648 "GET /static/admin/js/SelectBox.js HTTP/1.1" 304 0
INFO 2023-10-08 15:00:11,338 basehttp 824 10808 "GET /static/admin/js/prepopulate_init.js HTTP/1.1" 304 0
INFO 2023-10-08 15:00:11,345 basehttp 824 16820 "GET /static/admin/js/admin/DateTimeShortcuts.js HTTP/1.1" 304 0
INFO 2023-10-08 15:00:11,353 basehttp 824 15344 "GET /static/admin/js/change_form.js HTTP/1.1" 304 0
INFO 2023-10-08 15:00:11,356 basehttp 824 16820 "GET /static/admin/css/widgets.css HTTP/1.1" 200 11900
INFO 2023-10-08 15:00:11,427 basehttp 824 15344 "GET /static/admin/img/selector-icons.svg HTTP/1.1" 200 3291
INFO 2023-10-08 15:00:11,427 basehttp 824 11648 "GET /static/admin/img/icon-clock.svg HTTP/1.1" 200 677
INFO 2023-10-08 15:00:11,428 basehttp 824 16820 "GET /static/admin/img/icon-calendar.svg HTTP/1.1" 200 1086
INFO 2023-10-08 15:00:15,030 basehttp 824 10808 "GET /admin/auth/user/2/delete/ HTTP/1.1" 200 8338
INFO 2023-10-08 15:00:15,059 basehttp 824 15344 "GET /static/admin/js/cancel.js HTTP/1.1" 200 884
INFO 2023-10-08 15:00:17,375 basehttp 824 10808 "POST /admin/auth/user/2/delete/ HTTP/1.1" 302 0
INFO 2023-10-08 15:00:17,391 basehttp 824 10808 "GET /admin/auth/user/ HTTP/1.1" 200 12407
INFO 2023-10-08 15:00:17,426 basehttp 824 15344 "GET /admin/jsi18n/ HTTP/1.1" 200 16066
INFO 2023-10-08 15:00:20,494 basehttp 824 10808 "GET /admin/auth/user/ HTTP/1.1" 200 12220
INFO 2023-10-08 15:00:20,522 basehttp 824 15344 "GET /admin/jsi18n/ HTTP/1.1" 200 16066
INFO 2023-10-08 15:00:25,129 basehttp 824 10808 "GET /admin/auth/ HTTP/1.1" 200 5908
INFO 2023-10-08 15:00:26,625 basehttp 824 10808 "GET /admin/ HTTP/1.1" 200 8267
INFO 2023-10-08 15:00:26,688 basehttp 824 15344 "GET /static/admin/img/icon-deletelink.svg HTTP/1.1" 200 392
INFO 2023-10-08 15:00:32,976 basehttp 824 10808 "GET /admin/auth/user/2/change/ HTTP/1.1" 302 0
INFO 2023-10-08 15:00:32,991 basehttp 824 10808 "GET /admin/ HTTP/1.1" 200 8487
INFO 2023-10-08 15:00:33,040 basehttp 824 15344 "GET /static/admin/img/icon-alert.svg HTTP/1.1" 200 504
INFO 2023-10-08 15:00:38,149 basehttp 824 10808 "GET /admin/auth/user/2/change/ HTTP/1.1" 302 0
INFO 2023-10-08 15:00:38,161 basehttp 824 10808 "GET /admin/ HTTP/1.1" 200 8487
INFO 2023-10-08 15:00:40,599 basehttp 824 10808 "GET /admin/auth/user/2/change/ HTTP/1.1" 302 0
INFO 2023-10-08 15:00:40,632 basehttp 824 10808 "GET /admin/ HTTP/1.1" 200 8487
INFO 2023-10-08 15:00:44,566 basehttp 824 10808 "GET /admin/auth/user/ HTTP/1.1" 200 12220
INFO 2023-10-08 15:00:44,599 basehttp 824 15344 "GET /admin/jsi18n/ HTTP/1.1" 200 16066
INFO 2023-10-08 15:00:49,570 basehttp 824 10808 "GET /admin/auth/user/add/ HTTP/1.1" 200 11891
INFO 2023-10-08 15:00:49,603 basehttp 824 15344 "GET /admin/jsi18n/ HTTP/1.1" 200 16066
INFO 2023-10-08 15:01:26,536 basehttp 824 10808 "POST /admin/auth/user/add/ HTTP/1.1" 302 0
INFO 2023-10-08 15:01:26,565 basehttp 824 10808 "GET /admin/auth/user/3/change/ HTTP/1.1" 200 24256
INFO 2023-10-08 15:01:26,607 basehttp 824 15344 "GET /admin/jsi18n/ HTTP/1.1" 200 16066
INFO 2023-10-08 15:01:56,012 basehttp 824 10808 "POST /admin/auth/user/3/change/ HTTP/1.1" 302 0
INFO 2023-10-08 15:01:56,028 basehttp 824 10808 "GET /admin/auth/user/ HTTP/1.1" 200 12878
INFO 2023-10-08 15:01:56,095 basehttp 824 15344 "GET /admin/jsi18n/ HTTP/1.1" 200 16066
ERROR 2023-10-08 15:02:02,113 log 824 10808 Internal Server Error: /admin/online_shop/product/
Traceback (most recent call last):
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
sqlite3.OperationalError: no such table: online_shop_product

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\contrib\admin\options.py", line 688, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\utils\decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\views\decorators\cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\contrib\admin\sites.py", line 242, in inner
    return view(request, *args, **kwargs)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\utils\decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\contrib\admin\options.py", line 1926, in changelist_view
    cl = self.get_changelist_instance(request)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\contrib\admin\options.py", line 836, in get_changelist_instance
    return ChangeList(
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\contrib\admin\views\main.py", line 123, in __init__
    self.get_results(request)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\contrib\admin\views\main.py", line 279, in get_results
    result_count = paginator.count
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\utils\functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\core\paginator.py", line 93, in count
    return c()
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\db\models\query.py", line 608, in count
    return self.query.get_count(using=self.db)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\db\models\sql\query.py", line 568, in get_count
    return obj.get_aggregation(using, {"__count": Count("*")})["__count"]
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\db\models\sql\query.py", line 554, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
django.db.utils.OperationalError: no such table: online_shop_product
ERROR 2023-10-08 15:02:02,116 basehttp 824 10808 "GET /admin/online_shop/product/ HTTP/1.1" 500 180299
INFO 2023-10-08 15:02:04,408 basehttp 824 10808 "GET /admin/auth/user/ HTTP/1.1" 200 12648
ERROR 2023-10-08 15:09:25,225 log 824 12668 Internal Server Error: /admin/online_shop/product/
Traceback (most recent call last):
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
sqlite3.OperationalError: no such table: online_shop_product

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\contrib\admin\options.py", line 688, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\utils\decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\views\decorators\cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\contrib\admin\sites.py", line 242, in inner
    return view(request, *args, **kwargs)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\utils\decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\contrib\admin\options.py", line 1926, in changelist_view
    cl = self.get_changelist_instance(request)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\contrib\admin\options.py", line 836, in get_changelist_instance
    return ChangeList(
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\contrib\admin\views\main.py", line 123, in __init__
    self.get_results(request)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\contrib\admin\views\main.py", line 279, in get_results
    result_count = paginator.count
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\utils\functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\core\paginator.py", line 93, in count
    return c()
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\db\models\query.py", line 608, in count
    return self.query.get_count(using=self.db)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\db\models\sql\query.py", line 568, in get_count
    return obj.get_aggregation(using, {"__count": Count("*")})["__count"]
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\db\models\sql\query.py", line 554, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
django.db.utils.OperationalError: no such table: online_shop_product
ERROR 2023-10-08 15:09:25,229 basehttp 824 12668 "GET /admin/online_shop/product/ HTTP/1.1" 500 180299
INFO 2023-10-08 15:09:29,456 basehttp 824 12668 "GET /admin/auth/user/ HTTP/1.1" 200 12648
ERROR 2023-10-08 15:11:47,840 log 824 15520 Internal Server Error: /admin/online_shop/product/
Traceback (most recent call last):
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
sqlite3.OperationalError: no such table: online_shop_product

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\contrib\admin\options.py", line 688, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\utils\decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\views\decorators\cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\contrib\admin\sites.py", line 242, in inner
    return view(request, *args, **kwargs)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\utils\decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\contrib\admin\options.py", line 1926, in changelist_view
    cl = self.get_changelist_instance(request)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\contrib\admin\options.py", line 836, in get_changelist_instance
    return ChangeList(
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\contrib\admin\views\main.py", line 123, in __init__
    self.get_results(request)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\contrib\admin\views\main.py", line 279, in get_results
    result_count = paginator.count
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\utils\functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\core\paginator.py", line 93, in count
    return c()
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\db\models\query.py", line 608, in count
    return self.query.get_count(using=self.db)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\db\models\sql\query.py", line 568, in get_count
    return obj.get_aggregation(using, {"__count": Count("*")})["__count"]
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\db\models\sql\query.py", line 554, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
django.db.utils.OperationalError: no such table: online_shop_product
ERROR 2023-10-08 15:11:47,844 basehttp 824 15520 "GET /admin/online_shop/product/ HTTP/1.1" 500 180299
INFO 2023-10-08 15:11:49,256 basehttp 824 15520 "GET /admin/auth/user/ HTTP/1.1" 200 12648
INFO 2023-10-08 15:11:50,699 basehttp 824 15520 "GET /admin/auth/group/ HTTP/1.1" 200 8544
INFO 2023-10-08 15:11:50,731 basehttp 824 15520 "GET /admin/jsi18n/ HTTP/1.1" 200 16066
ERROR 2023-10-08 15:11:54,830 log 824 15520 Internal Server Error: /admin/online_shop/category/
Traceback (most recent call last):
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
sqlite3.OperationalError: no such table: online_shop_category

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\contrib\admin\options.py", line 688, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\utils\decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\views\decorators\cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\contrib\admin\sites.py", line 242, in inner
    return view(request, *args, **kwargs)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\utils\decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\contrib\admin\options.py", line 1926, in changelist_view
    cl = self.get_changelist_instance(request)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\contrib\admin\options.py", line 836, in get_changelist_instance
    return ChangeList(
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\contrib\admin\views\main.py", line 123, in __init__
    self.get_results(request)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\contrib\admin\views\main.py", line 279, in get_results
    result_count = paginator.count
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\utils\functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\core\paginator.py", line 93, in count
    return c()
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\db\models\query.py", line 608, in count
    return self.query.get_count(using=self.db)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\db\models\sql\query.py", line 568, in get_count
    return obj.get_aggregation(using, {"__count": Count("*")})["__count"]
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\db\models\sql\query.py", line 554, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
django.db.utils.OperationalError: no such table: online_shop_category
ERROR 2023-10-08 15:11:54,834 basehttp 824 15520 "GET /admin/online_shop/category/ HTTP/1.1" 500 180351
INFO 2023-10-08 15:11:57,835 basehttp 824 15520 "GET /admin/auth/group/ HTTP/1.1" 200 8544
ERROR 2023-10-08 15:13:38,249 log 824 15520 Internal Server Error: /admin/online_shop/product/add/
Traceback (most recent call last):
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
sqlite3.OperationalError: no such table: online_shop_category

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\template\defaulttags.py", line 238, in render
    nodelist.append(node.render_annotated(context))
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\template\loader_tags.py", line 208, in render
    return template.render(context)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\template\base.py", line 177, in render
    return self._render(context)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\template\defaulttags.py", line 238, in render
    nodelist.append(node.render_annotated(context))
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\template\defaulttags.py", line 238, in render
    nodelist.append(node.render_annotated(context))
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\template\defaulttags.py", line 321, in render
    return nodelist.render(context)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\template\defaulttags.py", line 321, in render
    return nodelist.render(context)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\template\base.py", line 1070, in render
    return render_value_in_context(output, context)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\template\base.py", line 1047, in render_value_in_context
    value = str(value)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\utils\html.py", line 420, in <lambda>
    klass.__str__ = lambda self: mark_safe(klass_str(self))
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\forms\boundfield.py", line 34, in __str__
    return self.as_widget()
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\forms\boundfield.py", line 107, in as_widget
    return widget.render(
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\forms\widgets.py", line 280, in render
    context = self.get_context(name, value, attrs)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\contrib\admin\widgets.py", line 320, in get_context
    "rendered_widget": self.widget.render(name, value, attrs),
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\forms\widgets.py", line 280, in render
    context = self.get_context(name, value, attrs)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\forms\widgets.py", line 758, in get_context
    context = super().get_context(name, value, attrs)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\forms\widgets.py", line 717, in get_context
    context["widget"]["optgroups"] = self.optgroups(
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\forms\widgets.py", line 657, in optgroups
    for index, (option_value, option_label) in enumerate(self.choices):
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\forms\models.py", line 1403, in __iter__
    for obj in queryset:
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\db\models\query.py", line 516, in _iterator
    yield from iterable
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
django.db.utils.OperationalError: no such table: online_shop_category
ERROR 2023-10-08 15:13:38,263 basehttp 824 15520 "GET /admin/online_shop/product/add/ HTTP/1.1" 500 610431
INFO 2023-10-08 15:13:45,631 basehttp 824 15520 "GET /admin/auth/group/ HTTP/1.1" 200 8544
INFO 2023-10-08 15:13:47,204 basehttp 824 15520 "GET /admin/online_shop/category/add/ HTTP/1.1" 200 9050
INFO 2023-10-08 15:13:47,236 basehttp 824 15520 "GET /admin/jsi18n/ HTTP/1.1" 200 16066
INFO 2023-10-08 15:13:50,440 basehttp 824 15520 "GET /admin/auth/group/ HTTP/1.1" 200 8544
INFO 2023-10-08 20:38:53,486 autoreload 1800 5296 Watching for file changes with StatReloader
WARNING 2023-10-08 20:38:56,462 log 1800 14920 Not Found: /
WARNING 2023-10-08 20:38:56,466 basehttp 1800 14920 "GET / HTTP/1.1" 404 4454
INFO 2023-10-08 20:38:59,148 basehttp 1800 14920 "GET /admin/auth/group/ HTTP/1.1" 200 8536
INFO 2023-10-08 20:38:59,338 basehttp 1800 14920 "GET /static/admin/img/search.svg HTTP/1.1" 200 458
INFO 2023-10-08 20:38:59,377 basehttp 1800 16080 "GET /static/admin/css/responsive.css HTTP/1.1" 200 18533
INFO 2023-10-08 20:38:59,380 basehttp 1800 19432 "GET /static/admin/js/filters.js HTTP/1.1" 200 978
INFO 2023-10-08 20:38:59,391 basehttp 1800 12228 "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
INFO 2023-10-08 20:38:59,392 basehttp 1800 2444 "GET /static/admin/img/tooltag-add.svg HTTP/1.1" 200 331
INFO 2023-10-08 20:39:01,501 basehttp 1800 14920 "GET /admin/auth/group/ HTTP/1.1" 200 8536
INFO 2023-10-08 20:39:01,536 basehttp 1800 12228 "GET /admin/jsi18n/ HTTP/1.1" 200 16066
INFO 2023-10-08 20:39:10,634 basehttp 1800 12228 "GET /admin/online_shop/goods/ HTTP/1.1" 200 11629
INFO 2023-10-08 20:39:10,669 basehttp 1800 12228 "GET /admin/jsi18n/ HTTP/1.1" 200 16066
INFO 2023-10-08 20:44:08,409 autoreload 1800 5296 D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\online_shop\models.py changed, reloading.
INFO 2023-10-08 20:44:08,867 autoreload 15296 10768 Watching for file changes with StatReloader
INFO 2023-10-08 21:04:09,373 autoreload 18488 1452 Watching for file changes with StatReloader
WARNING 2023-10-08 21:04:12,789 log 18488 9548 Not Found: /
WARNING 2023-10-08 21:04:12,790 basehttp 18488 9548 "GET / HTTP/1.1" 404 4454
INFO 2023-10-08 21:04:29,734 basehttp 18488 17104 "GET /admin/online_shop/goods/ HTTP/1.1" 200 12839
INFO 2023-10-08 21:04:29,935 basehttp 18488 17104 - Broken pipe from ('127.0.0.1', 63235)
INFO 2023-10-08 21:04:29,945 basehttp 18488 10220 "GET /static/admin/img/tooltag-add.svg HTTP/1.1" 200 331
INFO 2023-10-08 21:04:30,010 basehttp 18488 4672 "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
INFO 2023-10-08 21:04:34,015 basehttp 18488 10220 "GET /admin/online_shop/client/ HTTP/1.1" 200 13035
INFO 2023-10-08 21:04:34,058 basehttp 18488 10220 "GET /admin/jsi18n/ HTTP/1.1" 200 16066
INFO 2023-10-08 21:04:36,483 basehttp 18488 10220 "GET /admin/online_shop/goods/ HTTP/1.1" 200 12839
INFO 2023-10-08 21:04:36,516 basehttp 18488 10220 "GET /admin/jsi18n/ HTTP/1.1" 200 16066
INFO 2023-10-08 21:04:40,599 basehttp 18488 10220 "GET /admin/online_shop/order/ HTTP/1.1" 200 47695
INFO 2023-10-08 21:04:40,647 basehttp 18488 10220 "GET /admin/jsi18n/ HTTP/1.1" 200 16066
INFO 2023-10-08 21:05:18,858 autoreload 18488 1452 D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\online_shop\admin.py changed, reloading.
INFO 2023-10-08 21:05:19,393 autoreload 14716 14312 Watching for file changes with StatReloader
INFO 2023-10-08 21:05:56,223 basehttp 14716 15556 "GET /admin/online_shop/order/ HTTP/1.1" 200 47695
INFO 2023-10-08 21:05:56,579 basehttp 14716 6020 "GET /static/admin/css/changelists.css HTTP/1.1" 200 6566
INFO 2023-10-08 21:05:56,588 basehttp 14716 15556 "GET /static/admin/css/base.css HTTP/1.1" 200 21207
INFO 2023-10-08 21:05:56,601 basehttp 14716 9292 - Broken pipe from ('127.0.0.1', 63281)
INFO 2023-10-08 21:05:56,679 basehttp 14716 17556 "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
INFO 2023-10-08 21:05:56,689 basehttp 14716 8772 "GET /static/admin/img/tooltag-add.svg HTTP/1.1" 200 331
INFO 2023-10-08 21:05:59,674 basehttp 14716 17556 "GET /admin/online_shop/goods/ HTTP/1.1" 200 12839
INFO 2023-10-08 21:05:59,718 basehttp 14716 17556 "GET /admin/jsi18n/ HTTP/1.1" 200 16066
INFO 2023-10-08 21:06:01,495 basehttp 14716 17556 "GET /admin/online_shop/goods/10/change/ HTTP/1.1" 200 12535
INFO 2023-10-08 21:06:01,533 basehttp 14716 17556 "GET /admin/jsi18n/ HTTP/1.1" 200 16066
INFO 2023-10-08 21:06:01,537 basehttp 14716 8772 "GET /static/admin/js/change_form.js HTTP/1.1" 200 606
INFO 2023-10-08 21:06:01,537 basehttp 14716 11020 "GET /static/admin/js/prepopulate_init.js HTTP/1.1" 200 586
INFO 2023-10-08 21:06:01,544 basehttp 14716 17556 "GET /static/admin/css/widgets.css HTTP/1.1" 200 11900
INFO 2023-10-08 21:06:11,754 basehttp 14716 8772 "GET /admin/online_shop/goods/ HTTP/1.1" 200 12839
INFO 2023-10-08 21:06:11,803 basehttp 14716 8772 "GET /admin/jsi18n/ HTTP/1.1" 200 16066
INFO 2023-10-08 21:06:50,626 basehttp 14716 8772 "GET /admin/online_shop/goods/ HTTP/1.1" 200 12839
INFO 2023-10-08 21:06:50,662 basehttp 14716 8772 "GET /admin/jsi18n/ HTTP/1.1" 200 16066
INFO 2023-10-08 21:06:52,330 basehttp 14716 8772 "GET /admin/online_shop/client/ HTTP/1.1" 200 13035
INFO 2023-10-08 21:06:52,371 basehttp 14716 8772 "GET /admin/jsi18n/ HTTP/1.1" 200 16066
INFO 2023-10-08 21:08:32,167 autoreload 14716 14312 D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\online_shop\admin.py changed, reloading.
INFO 2023-10-08 21:08:32,712 autoreload 2976 7992 Watching for file changes with StatReloader
INFO 2023-10-08 21:09:29,010 autoreload 2976 7992 D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\online_shop\admin.py changed, reloading.
INFO 2023-10-08 21:09:29,521 autoreload 14528 13540 Watching for file changes with StatReloader
INFO 2023-10-08 21:10:08,062 autoreload 14528 13540 D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\online_shop\admin.py changed, reloading.
INFO 2023-10-08 21:10:08,600 autoreload 15828 11768 Watching for file changes with StatReloader
INFO 2023-10-08 21:10:32,707 autoreload 15828 11768 D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\online_shop\admin.py changed, reloading.
INFO 2023-10-08 21:10:33,172 autoreload 4352 6140 Watching for file changes with StatReloader
INFO 2023-10-08 21:12:05,490 autoreload 4352 6140 D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\online_shop\admin.py changed, reloading.
INFO 2023-10-08 21:12:05,967 autoreload 2736 10444 Watching for file changes with StatReloader
INFO 2023-10-08 21:19:57,964 autoreload 2736 10444 D:\Разработчик\ПОГРУЖЕНИЕ В PYTHON\my_shop\online_shop\admin.py changed, reloading.
INFO 2023-10-08 21:19:58,418 autoreload 11488 15008 Watching for file changes with StatReloader
INFO 2023-10-08 21:30:31,520 basehttp 11488 8720 "GET /admin/online_shop/client/ HTTP/1.1" 200 13035
INFO 2023-10-08 21:30:31,553 basehttp 11488 8720 "GET /admin/jsi18n/ HTTP/1.1" 200 16066
INFO 2023-10-08 21:30:36,000 basehttp 11488 8720 "GET /admin/online_shop/goods/ HTTP/1.1" 200 14883
INFO 2023-10-08 21:30:36,032 basehttp 11488 14840 "GET /admin/jsi18n/ HTTP/1.1" 200 16066
INFO 2023-10-08 21:30:36,087 basehttp 11488 15584 "GET /static/admin/img/search.svg HTTP/1.1" 200 458
INFO 2023-10-08 21:30:36,133 basehttp 11488 14840 "GET /static/admin/img/sorting-icons.svg HTTP/1.1" 200 1097
INFO 2023-10-08 21:30:47,712 basehttp 11488 8720 "GET /admin/online_shop/order/ HTTP/1.1" 200 49250
INFO 2023-10-08 21:30:47,748 basehttp 11488 14840 "GET /admin/jsi18n/ HTTP/1.1" 200 16066
INFO 2023-10-08 21:30:51,131 basehttp 11488 8720 "GET /admin/online_shop/client/ HTTP/1.1" 200 13035
INFO 2023-10-08 21:30:51,162 basehttp 11488 14840 "GET /admin/jsi18n/ HTTP/1.1" 200 16066
INFO 2023-10-08 21:30:56,199 basehttp 11488 8720 "GET /admin/online_shop/goods/ HTTP/1.1" 200 14883
INFO 2023-10-08 21:30:56,228 basehttp 11488 14840 "GET /admin/jsi18n/ HTTP/1.1" 200 16066
INFO 2023-10-08 21:31:01,227 basehttp 11488 8720 "GET /admin/online_shop/order/ HTTP/1.1" 200 49250
INFO 2023-10-08 21:31:01,253 basehttp 11488 14840 "GET /admin/jsi18n/ HTTP/1.1" 200 16066
